---
- name: Converge
  hosts: all
  
  pre_tasks:
    - name: Create man directory as a requirement for openjdk-11-jre-headless
      file: 
        path: /usr/share/man/man1/
        state: directory

  tasks:
    - name: "Include unimus"
      include_role:
        name: unimus
